services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env

  database:
    image: mysql:5.7
    container_name: restaurant_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: